{\rtf1\ansi\ansicpg1252\cocoartf1504\cocoasubrtf600
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red146\green154\blue158;\red25\green27\blue29;\red0\green0\blue0;
}
{\*\expandedcolortbl;\csgray\c100000;\cssrgb\c63922\c66667\c68235;\cssrgb\c12941\c14118\c14902;\csgenericrgb\c0\c0\c0;
}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl300\partightenfactor0

\f0\fs22 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 Traceback (most recent call last):\
  File "/Users/ethantom/Desktop/Coding_Dojo/python_stack/flask_MYSQL/friends/server.py", line 4, in <module>\
    mysql = MySQLConnector(app,'friendsdb')\
  File "/Users/ethantom/Desktop/Coding_Dojo/python_stack/flask_MYSQL/friends/mysqlconnection.py", line 40, in MySQLConnector\
    return MySQLConnection(app, db)\
  File "/Users/ethantom/Desktop/Coding_Dojo/python_stack/flask_MYSQL/friends/mysqlconnection.py", line 15, in __init__\
    DATABASE_URI = "mysql://\{\}:\{\}@127.0.0.1:\{\}/\{\}".format(config['user'], config['password'], config['port'], config['database'])\
KeyError: 'user'\
\cf4 \cb1 I removed the extra s\'92s.}